(() => {
  const $ = id => document.getElementById(id);
  const text = {
    es: {
      eyebrow:'Laboratorio interactivo · Regresión · 5 minutos', title:'Medir una predicción numérica', intro:'Explora los residuos y compara RMSE, MSE, MAE y R².', configure:'01 · Configura', dataTitle:'Datos', situationLabel:'Situación', modelLabel:'Modelo', plotTitle:'Predicciones y residuos', metricsTitle:'Métricas',
      situations:['Tendencia limpia','Con valores atípicos','Relación débil'], models:['Regresión lineal','Media constante'], fitHelp:'La recta minimiza MSE. Ambos modelos se ajustan y evalúan sobre estos mismos datos: esta actividad explica métricas, no mide generalización.', caption:'', units:'RMSE y MAE: unidades originales. MSE: unidades al cuadrado. R² no tiene unidades.', closing:'Medir también es decidir qué significa equivocarse.', challengeTitle:'Reto final', challengeCopy:'Elige Relación débil y compara Regresión lineal con Media constante. Observa qué modelo mejora más respecto a la media y explica por qué.', challengeButton:'Preparar el reto', input:'Entrada', output:'Valor',
      help:['Raíz del error cuadrático medio: vuelve a las unidades originales y da más peso a errores grandes.','Error cuadrático medio: promedio de los residuos al cuadrado.','Error absoluto medio: promedio de la magnitud de los residuos.','1 − error cuadrático total / variabilidad total. Compara el modelo con predecir siempre la media. R² puede ser negativo cuando el modelo funciona peor que una línea horizontal que representa la media de la variable objetivo; es decir, cuando sus errores son mayores que los de usar siempre ese valor medio.'],
      tabs:['1 · Métricas','2 · Valores atípicos','3 · R²'], labels:['Observa','Cambia','Compara','Piensa','Solución'],
      lessons:[['Del residuo a las métricas','Observa la tendencia limpia y los segmentos naranjas.','Cambia Regresión lineal → Media constante.','Compara los cuatro valores sobre los mismos datos.','¿Por qué un promedio de residuos cercano a cero puede ocultar errores grandes?','Los errores con signo se compensan. MAE usa valores absolutos y MSE los eleva al cuadrado; RMSE = √MSE. La media constante da R²=0 en estos mismos datos.'],['El efecto de un valor atípico','Selecciona Tendencia limpia y Regresión lineal.','Cambia únicamente a Con valores atípicos.','Observa la recta y el aumento de RMSE y MAE.','¿Qué métrica cambia más ante un error extremo?','MSE y RMSE dan mayor peso a errores grandes. MAE crece proporcionalmente. El atípico también influye en la recta porque se ajusta minimizando MSE.'],['La referencia de la media · Reto final','Selecciona Relación débil.','Alterna Regresión lineal y Media constante.','Compara cuánto mejora la recta respecto a la media.','¿Un R² alto garantiza un error absoluto pequeño?','No necesariamente. R² mide la mejora relativa frente a predecir la media, mientras MAE y RMSE miden el tamaño del error. En esta actividad, al evaluar sobre estos mismos datos, la media da R²=0. En otra evaluación, si el modelo funciona peor que una línea horizontal que representa la media de la variable objetivo, R² será negativo.']]
    },
    en: {
      eyebrow:'Interactive laboratory · Regression · 5 minutes', title:'Measuring a numerical prediction', intro:'Explore residuals and compare RMSE, MSE, MAE and R².', configure:'01 · Configure', dataTitle:'Data', situationLabel:'Scenario', modelLabel:'Model', plotTitle:'Predictions and residuals', metricsTitle:'Metrics',
      situations:['Clean trend','With an outlier','Weak relationship'],models:['Linear regression','Constant mean'],fitHelp:'The line minimizes MSE. Both models are fitted and evaluated on these same data: this activity explains metrics, rather than estimating generalization.',caption:'',units:'RMSE and MAE: original units. MSE: squared units. R² has no units.',closing:'Measuring also means deciding what it means to be wrong.',challengeTitle:'Final challenge',challengeCopy:'Choose Weak relationship and compare Linear regression with Constant mean. Observe which model improves most upon the mean and explain why.',challengeButton:'Set up challenge',input:'Input',output:'Value',
      help:['Root mean squared error: returns to the original units and gives more weight to large errors.','Mean squared error: the average squared residual.','Mean absolute error: the average magnitude of the residuals.','1 − total squared error / total variation. It compares the model with always predicting the mean. R² can be negative when the model performs worse than a horizontal line representing the mean of the target variable; that is, when its errors are larger than those from always using that mean.'],
      tabs:['1 · Metrics','2 · Outliers','3 · R²'],labels:['Observe','Change','Compare','Think','Solution'],
      lessons:[['From residuals to metrics','Observe the clean trend and the orange segments.','Switch Linear regression → Constant mean.','Compare all four values on the same data.','Why can an average residual near zero hide large errors?','Signed errors cancel out. MAE uses absolute values and MSE squares them; RMSE = √MSE. The constant mean gives R²=0 on these same data.'],['The effect of an outlier','Select Clean trend and Linear regression.','Change only the scenario to With an outlier.','Observe the line and the increase in RMSE and MAE.','Which metric changes more when an extreme error appears?','MSE and RMSE give more weight to large errors. MAE grows proportionally. The outlier also affects the line because fitting minimizes MSE.'],['The mean as a baseline · Final challenge','Select Weak relationship.','Switch between Linear regression and Constant mean.','Compare how much the line improves upon the mean.','Does a high R² guarantee a small absolute error?','Not necessarily. R² measures relative improvement over predicting the mean, while MAE and RMSE measure error size. In this activity, evaluating on these same data gives the mean R²=0. On another evaluation, if the model performs worse than a horizontal line representing the mean of the target variable, R² is negative.']]
    }
  };
  let lang='es', step=0, visible={observed:true,prediction:true,mean:true,residuals:true};
  function points(){let s=37;const r=()=>((s=(s*1664525+1013904223)>>>0)/4294967296);return Array.from({length:45},(_,i)=>{const x=i/44*10;let y=$('data').value==='weak'?5+.2*x+(r()-.5)*4:2+.85*x+(r()-.5)*1.4;if($('data').value==='outliers'&&i===41)y=15;return{x,y};});}
  function render(){const t=text[lang];document.documentElement.lang=lang;document.title=`RegressionLab · ${t.title}`;for(const id of ['eyebrow','title','intro','configure','dataTitle','situationLabel','modelLabel','fitHelp','plotTitle','metricsTitle','units','closing'])$(id).textContent=t[id];$('plotControls').innerHTML=(lang==='en'?[['observed','Observed values'],['prediction','Predictions'],['mean','Mean'],['residuals','Residuals']]:[['observed','Valores observados'],['prediction','Predicciones'],['mean','Media'],['residuals','Residuos']]).map(([k,label])=>`<button type=button data-layer="${k}" class="${visible[k]?'active':''}">${label}</button>`).join('');$('plotControls').querySelectorAll('button').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;visible[k]=!visible[k];b.classList.toggle('active',visible[k]);draw();});$('plotLegend').innerHTML=lang==='en'?'<span class=legend-point>● Observed values</span><span class=legend-line>━ Predictions</span><span class=legend-mean>┄ Mean of target variable</span><span class=legend-error>│ Residuals (observed − predicted)</span>':'<span class=legend-point>● Puntos verdes: valores observados</span><span class=legend-line>━ Línea azul: predicciones</span><span class=legend-mean>┄ Línea gris discontinua: media de la variable objetivo</span><span class=legend-error>│ Segmentos naranjas: residuos (observado − predicho)</span>';[...$('data').options].forEach((o,i)=>o.textContent=t.situations[i]);[...$('model').options].forEach((o,i)=>o.textContent=t.models[i]);$('tabs').innerHTML=t.tabs.map((x,i)=>`<button data-step="${i}" aria-current="${i===step}">${x}</button>`).join('');const g=t.lessons[step],open=$('guide').querySelector('details')?.open;$('guide').innerHTML=`<h2>${g[0]}</h2><div class="steps">${t.labels.slice(0,3).map((x,i)=>`<div><b class="step-label">${x}</b><p>${g[i+1]}</p></div>`).join('')}</div><div class="reflection"><b>${t.labels[3]}</b><p>${g[4]}</p></div><details class="solution" ${open?'open':''}><summary>${t.labels[4]}</summary><p>${g[5]}</p></details>`;draw();}
  function draw(){const t=text[lang],a=points(),mx=5,my=a.reduce((s,p)=>s+p.y,0)/a.length;const slope=$('model').value==='mean'?0:a.reduce((s,p)=>s+(p.x-mx)*(p.y-my),0)/a.reduce((s,p)=>s+(p.x-mx)**2,0),pred=x=>my+slope*(x-mx),mse=a.reduce((s,p)=>s+(p.y-pred(p.x))**2,0)/a.length,mae=a.reduce((s,p)=>s+Math.abs(p.y-pred(p.x)),0)/a.length,r2=1-mse/(a.reduce((s,p)=>s+(p.y-my)**2,0)/a.length);const values=[Math.sqrt(mse),mse,mae,r2],names=['RMSE','MSE','MAE','R²'];$('metrics').innerHTML=names.map((name,i)=>`<div class="metric"><small>${name}</small><strong>${values[i].toLocaleString(lang,{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><p class="help">${t.help[i]}</p></div>`).join('');const canvas=$('plot'),W=Math.max(280,Math.round(canvas.clientWidth)),H=380,bottom=H-50,left=42,right=W-18,sx=x=>left+x*(right-left)/10,sy=y=>bottom-y*(bottom-30)/16;canvas.width=W;canvas.height=H;const c=canvas.getContext('2d');c.clearRect(0,0,W,H);c.fillStyle='white';c.fillRect(0,0,W,H);c.font='14px system-ui';c.lineWidth=1;for(let x=0;x<=10;x+=2){c.strokeStyle='#dce2e3';c.beginPath();c.moveTo(sx(x),25);c.lineTo(sx(x),bottom);c.stroke();c.fillStyle='#536170';c.fillText(x,sx(x)-4,bottom+23);}for(let y=0;y<=16;y+=4){c.strokeStyle='#dce2e3';c.beginPath();c.moveTo(left,sy(y));c.lineTo(right,sy(y));c.stroke();c.fillStyle='#536170';c.fillText(y,10,sy(y)+5);}c.fillText(t.input,W-65,H-4);c.fillText(t.output,10,20);if(visible.mean){c.save();c.setLineDash([7,5]);c.strokeStyle='#879294';c.lineWidth=2;c.beginPath();c.moveTo(sx(0),sy(my));c.lineTo(sx(10),sy(my));c.stroke();c.setLineDash([]);c.fillStyle='#687577';c.font='12px system-ui';c.fillText(lang==='en'?'Mean':'Media',left+8,sy(my)-7);c.restore();}if(visible.prediction){c.strokeStyle='#18365d';c.lineWidth=3;c.beginPath();c.moveTo(sx(0),sy(pred(0)));c.lineTo(sx(10),sy(pred(10)));c.stroke();}for(const p of a){if(visible.residuals){c.strokeStyle='#e87f44';c.lineWidth=1;c.beginPath();c.moveTo(sx(p.x),sy(p.y));c.lineTo(sx(p.x),sy(pred(p.x)));c.stroke();}if(visible.observed){c.fillStyle='#118b85';c.beginPath();c.arc(sx(p.x),sy(p.y),5,0,Math.PI*2);c.fill();}}$('plot').setAttribute('aria-label',t.plotTitle);}
  $('language').addEventListener('change',()=>{lang=$('language').value;render();});for(const id of ['data','model'])$(id).addEventListener('change',draw);$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){step=Number(b.dataset.step);render();}});window.addEventListener('resize',draw);render();
})();
