(() => {
const dictionary={
'0,1':'0.1','Laboratorio':'Laboratory','Experimentos':'Experiments','Laboratorio interactivo · Modelos geométricos':'Interactive laboratory · Geometric models','¿Puedes predecir qué modelo':'Can you predict which model','funcionará?':'will work?','Cambia los datos, el algoritmo y unos pocos hiperparámetros clave. Observa la geometría de la frontera y descubre por qué los modelos se comportan de forma diferente.':'Change the data, algorithm and a few key hyperparameters. Observe the geometry of the boundary and discover why models behave differently.','Empezar experimento ↓':'Start experiment ↓','Mismos datos.':'Same data.','Distintas geometrías.':'Different geometries.','El laboratorio':'The laboratory','Datos → modelo → frontera → evaluación':'Data → model → boundary → evaluation','Empieza con un modelo de referencia sencillo. Después cambia una sola cosa y explica qué ha ocurrido.':'Start with a simple baseline model. Then change one thing and explain what happened.','Conjunto de datos':'Dataset','Lineal':'Linear','Lunas':'Moons','Círculos':'Circles','Grupos':'Clusters','Etiquetas incorrectas':'Incorrect labels','Cambia aleatoriamente la etiqueta de algunos ejemplos de entrenamiento sin modificar sus características.':'Randomly changes the labels of some training examples without changing their features.','Sin etiquetas modificadas':'No modified labels','↻ Nuevos datos':'↻ New data','ENTRENAMIENTO':'TRAINING','PRUEBA':'TEST','Regresión lineal':'Linear regression','referencia':'baseline','Regresión logística':'Logistic regression','Perceptrón':'Perceptron','Hiperparámetros':'Hyperparameters','Modelo de referencia sin hiperparámetros en este laboratorio.':'Baseline model with no hyperparameters in this laboratory.','💡 ¿Qué está ocurriendo?':'💡 What is happening?','Empieza simple. ¿Qué gana realmente un modelo más complejo?':'Start simple. What does a more complex model actually gain?','Espacio de decisión':'Decision space','clase 0':'class 0','clase 1':'class 1','Ocultar errores':'Hide errors','Mostrar errores':'Show errors','El color es la etiqueta que ve el modelo. Un anillo negro señala una etiqueta modificada.':'Color shows the label seen by the model. A black ring marks a modified label.','Evaluación':'Evaluation','Precisión':'Precision','Recall (exhaustividad)':{es:'Exhaustividad (Recall)',en:'Recall'},'Ejecuta el modelo para calcular las métricas sobre el conjunto de prueba.':'Run the model to calculate metrics on the test set.','▶ Ejecutar modelo':'▶ Run model','RETO DEL ESTUDIANTE':'STUDENT CHALLENGE','No busques el algoritmo que gana. Explica por qué cambia.':'Explain why the result changes, beyond choosing the winning algorithm.','Referencia':'Baseline','Lineal → logística':'Linear → logistic','Flexibilidad':'Flexibility','Convergencia':'Convergence','Perceptrón: 10 → 100':'Perceptron: 10 → 100','Regularización':'Regularization','SVM: C, γ y etiquetas erróneas':'SVM: C, γ and incorrect labels','Sin etiquetas':'Without labels',
'Modelo de referencia sin hiperparámetros en este laboratorio. Se ajusta a 0/1 y usa un umbral fijo de 0,5 solo para visualizar una clasificación.':'Baseline model with no hyperparameters here. It fits 0/1 targets and uses a fixed 0.5 threshold only to visualize classification.','Clasificador lineal probabilístico. En este laboratorio mantenemos C=1 para usarlo como referencia estable.':'Probabilistic linear classifier. We keep C=1 as a stable baseline.','Clasificador lineal que actualiza sus pesos cuando comete errores.':'Linear classifier that updates its weights when it makes errors.','Clasifica según los k vecinos más próximos del conjunto de entrenamiento.':'Classifies using the k nearest neighbors in the training set.','Busca una frontera de margen amplio; con RBF puede producir fronteras no lineales.':'Seeks a wide-margin boundary; RBF enables nonlinear boundaries.','Agrupa los datos sin usar etiquetas y actualiza centroides iterativamente.':'Groups data without labels and iteratively updates centroids.','Sin hiperparámetros':'No hyperparameters','Referencia sencilla: el umbral 0,5 es fijo.':'Simple baseline: the 0.5 threshold is fixed.','Sin controles':'No controls','Usamos C=1 fijo para comparar una frontera lineal estable con modelos más flexibles.':'We fix C=1 to compare a stable linear boundary with more flexible models.','Máximo de iteraciones':'Maximum iterations','Controla:':'Controls:','Observa:':'Observe:','cuántas pasadas sobre los datos puede realizar.':'how many passes over the data are allowed.','más iteraciones no convierten una frontera lineal en no lineal.':'more iterations do not turn a linear boundary into a nonlinear one.','k · número de vecinos':'k · number of neighbors','cuántos vecinos votan.':'how many neighbors vote.','k pequeño → frontera local; k grande → frontera más suave.':'small k → local boundary; large k → smoother boundary.','Kernel':{es:'Núcleo (Kernel)',en:'Kernel'},'la forma de medir similitud.':'how similarity is measured.','RBF permite fronteras no lineales.':'RBF allows nonlinear boundaries.','C · penalización de errores':'C · error penalty','cuánto se penalizan los errores.':'how strongly errors are penalized.','C pequeño → más regularización; C grande → mayor ajuste.':'small C → more regularization; large C → closer fit.','γ · localidad RBF':'γ · RBF locality','cuán local es la similitud.':'how local similarity is.','γ pequeño → efecto global; γ grande → efecto local.':'small γ → global effect; large γ → local effect.','k · número de grupos':'k · number of clusters','cuántos grupos debe buscar k-Means.':'how many clusters k-Means should find.','pocos grupos fusionan; demasiados pueden fragmentar.':'too few clusters merge groups; too many can fragment them.',
'Empieza simple: úsala como referencia y observa qué gana realmente un clasificador más adecuado.':'Start simple: use it as a baseline and see what a more suitable classifier actually gains.','Referencia lineal estable. Compárala con kNN y SVM cuando la geometría deje de ser lineal.':'Stable linear baseline. Compare it with kNN and SVM when the geometry is no longer linear.','Entrenamiento corto: ¿la frontera ya se ha estabilizado?':'Short training: has the boundary stabilized yet?','Valor de referencia: si los datos son separables, debería converger pronto.':'Baseline value: if the data are separable, it should converge quickly.','Más iteraciones no aumentan la capacidad: una frontera lineal sigue siendo lineal.':'More iterations do not increase capacity: a linear boundary remains linear.','k=1: frontera muy local y flexible; observa si persigue etiquetas incorrectas.':'k=1: a very local, flexible boundary; observe whether it follows incorrect labels.','k=5: equilibrio razonable entre detalle local y estabilidad.':'k=5: a reasonable balance between local detail and stability.','k=25: frontera suave; comprueba si desaparecen estructuras útiles.':'k=25: a smooth boundary; check whether useful structures disappear.','k=2: ¿estamos fusionando grupos diferentes?':'k=2: are we merging distinct groups?','k=3: compara los grupos encontrados con la estructura geométrica.':'k=3: compare the clusters found with the geometric structure.','k=5: la inercia puede bajar aunque estemos fragmentando grupos; mira Silhouette.':'k=5: inertia may decrease even when we fragment groups; inspect Silhouette.','Colores = grupos de k-Means':'Colors = k-Means clusters','etiqueta modificada':'modified label','Etiqueta modificada':'Modified label','Inercia':'Inertia','k-Means ignora las etiquetas. Comprueba si el clustering cambia aunque algunas etiquetas estén modificadas.':'k-Means ignores labels. Check whether clustering changes when some labels are modified.','Ejecuta k-Means para calcular inercia y Silhouette.':'Run k-Means to calculate inertia and Silhouette.','Ejecuta el modelo para calcular F1, precisión y recall sobre el conjunto de prueba.':'Run the model to calculate F1, precision and recall on the test set.','◎ Caso SVM':'◎ SVM case','Carga el caso reproducible SVM con 30% de etiquetas incorrectas':'Load the reproducible SVM case with 30% incorrect labels','Caso SVM de referencia cargado. Mantén RBF y γ=1; cambia solo C: 0,1 → 1 → 10. El modelo aprende con 25 etiquetas alteradas y se evalúa contra la clase real.':'SVM reference case loaded. Keep RBF and γ=1; change only C: 0.1 → 1 → 10. The model learns from 25 altered labels and is evaluated against the true class.'
};
const sentences={
'C bajo: SVM tolera mejor discrepancias en las etiquetas de entrenamiento. Puede ignorar parte del ruido y conservar una frontera más estable.':'Low C: SVM tolerates discrepancies in training labels better. It can ignore some noise and maintain a more stable boundary.',
'C alto: SVM intenta ajustarse con más fuerza a las etiquetas de entrenamiento, incluidas las incorrectas. Esto puede empeorar su rendimiento respecto a la clase real.':'High C: SVM tries harder to fit training labels, including incorrect ones. This may reduce performance against the true class.',
'C=1: compromiso entre margen y ajuste a las etiquetas de entrenamiento, algunas de las cuales son incorrectas.':'C=1: a compromise between margin and fitting training labels, some of which are incorrect.',
'C bajo: más regularización y más errores tolerados.':'Low C: more regularization and more errors tolerated.',
'C alto: penaliza más los errores de entrenamiento y busca un ajuste más estricto.':'High C: penalizes training errors more and seeks a closer fit.',
'C=1: compromiso entre margen y ajuste.':'C=1: a compromise between margin and fit.',
'γ bajo: similitud global y frontera suave.':'Low γ: global similarity and a smooth boundary.',
'γ alto: similitud local y frontera flexible.':'High γ: local similarity and a flexible boundary.',
'γ=1: localidad intermedia.':'γ=1: intermediate locality.',
'Kernel lineal: la frontera seguirá siendo recta.':'Linear kernel: the boundary remains straight.',
'El modelo aprende con las etiquetas mostradas; F1, precisión y recall se calculan respecto a la clase real.':'The model learns from the displayed labels; F1, precision and recall are calculated against the true class.'};
function dynamic(s,l){let m;if((m=s.match(/^(Lineal|Lunas|Círculos|Grupos|Linear|Moons|Circles|Clusters) · 70\/30(?: · (\d+) (etiquetas modificadas|modified labels))?$/))){const names={Lineal:['Lineal','Linear'],Linear:['Lineal','Linear'],Lunas:['Lunas','Moons'],Moons:['Lunas','Moons'],Círculos:['Círculos','Circles'],Circles:['Círculos','Circles'],Grupos:['Grupos','Clusters'],Clusters:['Grupos','Clusters']};return names[m[1]][l==='en'?1:0]+' · 70/30'+(m[2]?` · ${m[2]} ${l==='en'?'modified labels':'etiquetas modificadas'}`:'');}if(l!=='en')return null;
if((m=s.match(/^(\d+) etiquetas de entrenamiento modificadas$/)))return `${m[1]} modified training labels`;
if((m=s.match(/^Clase original: (\d+) → etiqueta usada: (\d+)$/)))return `Original class: ${m[1]} → label used: ${m[2]}`;
if(s.startsWith('F1 entrenamiento (clase real): '))return s.replace('F1 entrenamiento (clase real): ','Training F1 (true class): ').replace(' · F1 prueba: ',' · Test F1: ').replace(' → posible sobreajuste.',' → possible overfitting.').replace(' → generalización razonable.',' → reasonable generalization.').replace('% de las etiquetas de entrenamiento están modificadas: el modelo se entrena con ellas, pero estas métricas se calculan respecto a la clase real.','% of training labels are modified: the model trains on them, but these metrics use the true class.').replace('Caso reproducible: seed 65 · RBF · γ=1 · compara C=0,1 → 1 → 10.','Reproducible case: seed 65 · RBF · γ=1 · compare C=0.1 → 1 → 10.');
if(/^(C bajo:|C alto:|C=1:)/.test(s)){let result=s;for(const [es,en]of Object.entries(sentences))result=result.replace(es,en);return result;}return null;}
LabLanguage.init({dictionary,dynamic,titles:{es:'GeometricLab · Modelos geométricos',en:'GeometricLab · Geometric models'}});
})();
